enum ErrorCode {
    JWT_EXPIRED = "JWT_EXPIRED",
    UNAUTHORIZED = "UNAUTHORIZED",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
}

export default ErrorCode;
